# Generated by Django 4.1.5 on 2023-01-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_country_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
