# Generated by Django 4.1.5 on 2023-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=250)),
                ('companyName', models.CharField(max_length=250)),
                ('companyAddress', models.CharField(max_length=250)),
                ('jobDesc', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibilties', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('companyWebsite', models.CharField(max_length=250)),
                ('companyEmail', models.CharField(max_length=250)),
                ('companyContact', models.CharField(max_length=20)),
                ('salaryPackage', models.CharField(max_length=250)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highestEdu',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobCategory',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobDesc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobType',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
