# Generated by Django 4.1.5 on 2023-01-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_jobdesc_jobdetails_jobdesccomp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='companyId',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='userID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
            preserve_default=False,
        ),
    ]
