# Generated by Django 4.1.5 on 2023-01-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDetailsComp',
        ),
    ]
