# Generated by Django 4.1.5 on 2023-01-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_jobdetailscomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='userID',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='compID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
