# Generated by Django 4.1.5 on 2023-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_jobdetail_userid_jobdetail_compid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='logoPic',
            field=models.ImageField(default='', upload_to='app/company/logo'),
            preserve_default=False,
        ),
    ]
