# Generated by Django 4.1.5 on 2023-01-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobdetail_logopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetail')),
            ],
        ),
    ]
